---

# Travis file for mysql-server role

language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
  - "cp ./tests/ansible.cfg ./"

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/inventory tests/test_travis_first.yml --syntax-check

  # Run the role/playbook with ansible-playbook.
  # Use this playbook because root password change is needed only during
  # first run
  - "ansible-playbook -i tests/inventory tests/test_travis_first.yml --connection=local --sudo"

  # Add debug to show changed tasks count
  -  ansible-playbook -i tests/inventory tests/test_travis_second.yml --connection=local --sudo

  # Run the role/playbook again, checking to make sure it's idempotent.
  # Set change=1 or 2 or 3 due to non-interactive setup, travis also view change
  # on root password for server hostname (...) and to a bug in ansible
  # service module always return changed
  - >
    ansible-playbook -i tests/inventory tests/test_travis_second.yml --connection=local --sudo
    | grep -q 'changed=[0123].*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Check mysql-server service is running
  - "sudo service mysql status"

